### ISSUE TITLE
基于和风天气 API 的 Telegram 机器人

### ISSUE THREAD

**Issue by daya0576** [qwd/dev-site#10]
**项目名称：**
QWeatherBot

**作者：** 
daya0576

**作者URL：**
https://github.com/daya0576

**项目一句话简介：**
基于和风天气 API 的 Telegram 机器人

**主要开发语言：** （请只填写一种主要开发语言）
Python

**项目地址：** （不一定是Github，任何能让大家查看和下载的地方都可以）
https://github.com/daya0576/he-weather-bot

**Comment by QWRDA** [comment]
感谢分享👏，如果方便的话，请将项目中的英文名称HeWeather更改为我们的新名字QWeather（这不是强制要求）。我们将在近期版本更新的时候将你的代码加入我们的代码库。

**Comment by daya0576** [comment]
👏👏👏已更新
