### ISSUE TITLE
Flutter Plugin

### ISSUE THREAD

**Issue by CyJaySong** [qwd/dev-site#25]
**项目名称：flutter_qweather

**作者：CyJaySong

**作者URL：https://github.com/CyJaySong/

**项目一句话简介：Flutter 和风天气插件 ,支持安卓和iOS平台

**主要开发语言：Dart

**项目地址：[Github](https://github.com/fluttercandies/flutter_qweather) [pub.dev](https://pub.dev/packages/flutter_qweather)

**Comment by QWRDA** [comment]
感谢分享，正在添加ing

**Comment by CyJaySong** [comment]
由于我认证的开发者权限不够，部分需要特殊权限的Api没测试，若是用户反馈有问题，可引导用户至github，我根据反馈修正，我今后会持续根据和风的SDK更新插件
