### ISSUE TITLE
请问开发平台网站是否有英文版本

### ISSUE THREAD

**Issue by sbwww** [qwd/dev-site#3]
我在 [public-apis](https://github.com/public-apis/public-apis) 上发 PR 推荐了和风天气。请问本开发平台网站是否有英文版本，或者是否有团队正在进行此工作。

**Comment by guox** [comment]
多语言网站已经在准备中，我们计划将在年底随着新版本一并发布，🙏

**Comment by sbwww** [comment]
好耶 😄  期待一波
