### ISSUE TITLE
夏风天气（基于和风天气SDK开发）

### ISSUE THREAD

**Issue by SakurajimaMaii** [qwd/dev-site#31]
**项目名称：夏风天气**

**作者：Vast Gui** 

**作者URL：https://github.com/SakurajimaMaii**

**项目一句话简介：一款基于MVVM架构开发的天气应用，提供近十天天气预报，空气质量查看以及城市搜索等功能**

**主要开发语言：Kotlin** 

**项目地址：https://github.com/SakurajimaMaii/XiaFengWeather**

**Comment by QWRDA** [comment]
感谢分享，将在下次更新时添加到开发文档中。
