### ISSUE TITLE
tianditu_piece 集成了和风天气api的地图项目，希望能分享

### ISSUE THREAD

**Issue by ymzcode** [qwd/dev-site#50]
**项目名称：** tianditu_piece

**作者：** 随机的布尔值

**作者URL：** https://github.com/ymzcode

**项目一句话简介：** 一个集成了和风天气api的地图开源项目，可在线调试

**主要开发语言：** vue

**项目地址：** https://github.com/ymzcode/tianditu_piece

**Comment by QWRDA** [comment]
感谢你的分享，然而我们更希望开发者能够提供的作品可以更好的帮助其他人了解或学习如何使用我们的服务。所以，有没有可能将您在地图上解析天气数据的方法单独作为一个项目分享出来呢？

另外，vue是一种框架，而非语言。

最后，当你决定再次分享时，请直接修改[这个文件](https://github.com/qwd/dev-site/blob/master/_data/showcase.yml)，在本地验证后提交PR即可。

再次感谢你的反馈😄
