### ISSUE TITLE
加密签名及WebAPI相关的内容描述不清

### ISSUE THREAD

**Issue by floyd-li** [qwd/dev-site#98]
以查询[每日天气](https://dev.qweather.com/docs/api/weather/weather-daily-forecast/)功能的JavaScript代码为例，需要通过以下代码才可以正常请求：

```javascript
const now = Math.floor(Date.now() / 1000)
let parameters = {
    username: PUBLIC_ID,
    location: LOCATION_ID,
    t: now
  }
const sign = getSignature(parameters, PRIVATE_KEY)
const url = `https://devapi.qweather.com/v7/weather/3d?location=${LOCATION_ID}&username=${PUBLIC_ID}&t=${now}&sign=${sign}`
// 请求url获取对应数据...
```

而文档上对该接口请求参数的说明为：

> 请求参数包括必选和可选参数，参数之间使用`&`进行分隔。
> 
>    `location` *(必选)* 需要查询地区的[LocationID](https://dev.qweather.com/docs/resource/glossary/#locationid)或以英文逗号分隔的[经度,纬度坐标](https://dev.qweather.com/docs/resource/glossary/#coordinate)（十进制，最多支持小数点后两位），LocationID可通过[城市搜索](https://dev.qweather.com/docs/api/geoapi/)服务获取。例如 `location=101010100` 或 `location=116.41,39.92`
>
>    `key` *(必选)* 用户认证key，请参考[如何获取你的KEY](https://dev.qweather.com/docs/configuration/project-and-key/)。支持[数字签名](https://dev.qweather.com/docs/resource/signature-auth/)方式进行认证。例如 `key=123456789ABC`
>
>    `lang` 多语言设置，更多语言可选值参考[语言代码](https://dev.qweather.com/docs/resource/language/)。当数据不匹配你设置的语言时，将返回英文或其本地语言结果。
>
>    `unit` 数据单位设置，可选值包括`unit=m`（公制单位，默认）和`unit=i`（英制单位）。更多选项和说明参考[度量衡单位](https://dev.qweather.com/docs/resource/unit)。

以上说明非常容易让开发者认为请求接口时，*只允许传入以上四个参数*。

而在[加密签名认证](https://dev.qweather.com/docs/resource/signature-auth/)文档中，给出的签名参数是：

> `publicid`: 公共ID，每个KEY都对应一个公共ID，可在[控制台](https://console.qweather.com/)查看
> 
> `t`: 时间戳，秒级

> `sign`: 数字签名

实际上，在请求WebAPI时，需要传入其他的参数，同时`publicid`字段似乎也和给出的`JavaScript`示例代码中的`username`字段不统一。

在网上搜寻了各种资料，都没有找到对应的说明，最终是在 https://github.com/Ink-33/Weather-Sign/blob/master/index.php#L63 这里找到了对应的代码片段才得以完成开发。

希望贵团队可以完善相关文档，方便后续其他开发者的开发工作。

**Comment by QWRDA** [comment]
感谢提醒，已经修改了publicid名称问题 #99
